name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    name: Comprehensive Test with OceanBase 4.3.5
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      run: |
        pip install poetry
        
    - name: Install dependencies
      run: |
        poetry install --with lint,typing,test,test_integration

    - name: Install additional test dependencies
      run: |
        poetry run pip install langchain-community

    - name: Start OceanBase 4.3.5 container
      run: |
        set -e
        export tag="4.3.5"
        echo "Starting OceanBase container with tag ${tag}"
        docker run -id --name "langchain_oceanbase_test" \
          -e MODE=mini \
          -e OB_SERVER_IP=127.0.0.1 \
          -p 2881:2881 \
          oceanbase/oceanbase-ce:4.3.5-lts
        echo "OceanBase container started"

    - name: Wait for OceanBase to be ready
      run: |
        set -e
        echo "Waiting for OceanBase to be ready..."
        timeout=600  # 10 minutes timeout
        start_time=$(date +%s)
        
        while [ $timeout -gt 0 ]; do
          current_time=$(date +%s)
          elapsed=$((current_time - start_time))
          echo "Elapsed time: ${elapsed}s, remaining timeout: ${timeout}s"
          
          # Check if the container is still running
          if ! docker ps | grep -q "langchain_oceanbase_test"; then
            echo "Container is not running!"
            docker logs langchain_oceanbase_test
            exit 1
          fi
          
          # Check for boot success message
          if docker logs langchain_oceanbase_test 2>&1 | grep -q "boot success!"; then
            echo "OceanBase is ready!"
            break
          fi
          
          sleep 10
          timeout=$((timeout - 10))
        done
        
        if [ $timeout -le 0 ]; then
          echo "OceanBase did not start in time!"
          echo "Container logs:"
          docker logs langchain_oceanbase_test
          exit 1
        fi

    - name: Configure OceanBase for vector operations
      run: |
        set -e
        echo "Configuring OceanBase for vector operations..."
        
        # Wait a bit more for the database to be fully ready
        sleep 30
        
        # Set vector memory limit
        docker exec langchain_oceanbase_test obclient -h127.0.0.1 -P2881 -uroot@test -p'' \
          -e "ALTER SYSTEM ob_vector_memory_limit_percentage = 30;" || echo "Vector memory config may have failed, continuing..."
        
        # Create test database if needed
        docker exec langchain_oceanbase_test obclient -h127.0.0.1 -P2881 -uroot@test -p'' \
          -e "CREATE DATABASE IF NOT EXISTS test;" || echo "Database creation may have failed, continuing..."
          
        echo "OceanBase configuration completed"

    - name: Run comprehensive tests
      run: |
        set -e
        echo "Running comprehensive tests..."
        poetry run python tests/test_comprehensive.py

    - name: Run integration tests
      run: |
        set -e
        echo "Running integration tests..."
        poetry run python -m pytest tests/integration_tests/ -v

    - name: Cleanup and show results
      if: always()
      run: |
        echo "Test completed. Cleaning up..."
        
        # Show container logs if needed
        if docker ps -a | grep -q "langchain_oceanbase_test"; then
          echo "=== OceanBase Container Status ==="
          docker ps -a | grep langchain_oceanbase_test || true
          
          echo "=== OceanBase Container Logs (last 50 lines) ==="
          docker logs --tail 50 langchain_oceanbase_test || true
        fi
        
        # Clean up container
        docker rm -f langchain_oceanbase_test || true
        
        echo "Cleanup completed"

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test.result }}" == "success" ]; then
            echo "🎉 All tests passed successfully!"
            echo "✅ Comprehensive tests passed"
            echo "✅ Unit tests passed"
            echo "✅ Integration tests passed"
            echo "✅ All index types tested (HNSW, IVF, FLAT)"
            echo "✅ All metric types tested (l2, inner_product, cosine)"
            echo "✅ Basic functionality tests passed"
            echo "✅ Metadata preservation tests passed"
            echo "✅ OceanBase 4.3.5 compatibility confirmed"
          else
            echo "❌ Some tests failed!"
            echo "Please check the logs above for details."
            exit 1
          fi
